### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit.web'

### ISSUE THREAD

**Issue by SeekPoint** [kennethleungty/Pyvis-Network-Graph-Streamlit#1]
PS C:\react-graph\Pyvis-Network-Graph-Streamlit> streamlit run .\pyvis_network_app.py
Traceback (most recent call last):
  File "c:\python380\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python380\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python380\Scripts\streamlit.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'streamlit.web'

**Comment by kennethleungty** [comment]
Hi @loveJasmine, thanks for highlighting the issue. I have updated the versions in the requirements.txt. Essentially, just use the latest versions of the packages listed in the requirements, and it should work. Besides functioning locally (after testing on my own machine), I rebooted the app on Streamlit Cloud, so the demo works online too.
